#!/usr/bin/env bash
# A Bash script that loops indefinitely and ignores SIGTERM by printing a message

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

